### ISSUE TITLE
Agregar una foto al miembro de una cuadrilla

### ISSUE THREAD

**Issue by edvm** [edvm/ffhq#10]
En el modelo cuadrilla.models.Bombero , agregar un campo / ImageField opcional, para poder guardar la foto del bombero.

**Comment by jcarizza** [comment]
La doc de ImageField:
https://docs.djangoproject.com/en/1.7/ref/models/fields/#imagefield

Quizas necesiten un par de librerias extras como `libjpeg-devel`, `freetype-devel `,  `libpng-devel`, etc.

Si tienen problemas escriban aca o a mi mail por si se traban con algo.
