### ISSUE TITLE
Cuadrilla/models.py errores ortográficos

### ISSUE THREAD

**Issue by rafaelferrero** [edvm/ffhq#13]
Line 70: 'Numero del Hamdy' -> 'Numero del Handy' 
   (también en cuadrilla/forms.py line 67)
   (también en cuadrilla/migrations/0001_initial.py line 32)
Line 102: 'Conductor nauticuo' -> 'Conductor nautico'
   (también en cuadrilla/migrations/0001_initial.py line 40)
Line 111: 'Vencimiento dwl carnet de conducir' -> 'Vencimiento del carnet de conducir'
   (también en cuadrilla/migrations/0001_initial.py line 42)

**Comment by edvm** [comment]
Como vamos con esto? :)

**Comment by Theviajerock** [comment]
Bieen andaba algo perdido porque se me daño el pc personal entonces ando
conectandome solo del trabajo... Mañana espero terminar esto pero tengo una
duda... Hoy solo corregì una palabra para probar el funcionamiento de
github y ya me quedo claro, tambien corrijo tildes ? las reconoce sin
problemas el sistema? ( Disculpa la ignorancia, apenas voy cogiendole el
tiro a los detalles con el lenguaje)

Saludos!

2015-02-17 19:33 GMT-05:00 Emiliano Dalla Verde Marcozzi <
notifications@github.com>:

> Como vamos con esto? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edvm/ffhq/issues/13#issuecomment-74786904>.
>



-- 

*Victor Andres Martinez Hernandez*
*Programador y administrador de redes.*

**Comment by edvm** [comment]
Buenas Victor, no estoy seguro si va a pinchar o no, cuestion de probar ;), si al probar te pincha/revienta, fijate de anteponer u'está es mi cadená con múchos tíldes'
Saludso!
