### ISSUE TITLE
Configuración de Summernote

### ISSUE THREAD

**Issue by surrealcristian** [edvm/ffhq#14]
- ¿Qué botones del toolbar se quieren utilizar?
- ¿Usar airmode? (http://summernote.org/#/example#airmode)

**Comment by edvm** [comment]
Buenas Cristian! Gracias por el issue y por estar trabajando en esto. Por favor dejar los botones por default, theme por default y no utilizar airmode.
Muchas gracias!

**Comment by surrealcristian** [comment]
Por error agregué el commit de éste issue, en pull request de la rama issue-5.
Mergeando issue-5, éste issue quedaría completo.

**Comment by edvm** [comment]
Cerrado en https://github.com/edvm/ffhq/pull/15 #15
