### ISSUE TITLE
Error en manage.py

### ISSUE THREAD

**Issue by surrealcristian** [edvm/ffhq#3]
Al correr el comando "python3 manage.py --help", tengo el siguiente error:

    ImportError: No module named 'crispy_forms_materialize'

Si comento ese módulo en INSTALLED_APPS, el comando responde.

Estoy haciendo algo mal?

**Comment by edvm** [comment]
Epa, tiene sentido. Falta instalar crispy_forms_materialize, el cual esta
super alpha
porque lo voy codeando a medida que avanzo con los forms, por eso no lo
puse aun en
pypi como un package. crispy_forms_materialize es un template pack para
django crispy forms que hace que los forms se vean con los estilos de
materializecss.
Para instalarlo, recomiendo:
1- Clonar el repo: git clone
https://github.com/edvm/crispy-forms-materialize.git
2- Activar el virtualenv e instalar el repo de crispy-forms-materialize con
el comando:
$: python setup.py develop
Esto ultimo crea un symlink al directorio donde clonaste
crispy-forms-materialize.
Proba con eso, deberia funcionar :)

2015-02-02 18:41 GMT-03:00 surrealcristian <notifications@github.com>:

> Al correr el comando "python3 manage.py --help", tengo el siguiente error:
>
> ImportError: No module named 'crispy_forms_materialize'
>
> Si comento ese módulo en INSTALLED_APPS, el comando responde.
>
> Estoy haciendo algo mal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edvm/ffhq/issues/3>.
>



-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by surrealcristian** [comment]
Listo, lo hice andar.

Gracias por lo de "python setup.py develop", no sabía cómo funcionaba.
