### ISSUE TITLE
Implementar Django-Summernote ordenar los fields del form de alta de nuevo miembro de cuadrilla

### ISSUE THREAD

**Issue by edvm** [edvm/ffhq#5]
En el file cuadrilla/forms.py esta el form para poder dar de alta un nuevo miembro de la cuadrilla/destacamento (por ej un bombero). En el mismo, los fields/campos del formulario estan mal ordenados. Acomodar/juntar los fields que estan relacionados. Por ejemplo, es piola completar Nombre, Apellido, Edad, Domicilio uno detras del otro. Un mal ejemplo/practica es completar el Nombre al principio del formulario, y tener el campo/input del apellido al final del formulario. El orden de los campos se define mediante crispy_forms en la instancia del objeto 'layout' (self.helper.layour). Ademas de acomodar el orden de los fields, implementar https://github.com/summernote/django-summernote para los fields que son de tipo Textfield. Cualquier duda preguntar a Emiliano.

**Comment by jcarizza** [comment]
@surrealcristian Avisa si te trabaste con algo asi te ayudamos.

**Comment by surrealcristian** [comment]
No tuve tiempo de sentarme a resolver el issue.
Éste finde me pongo con eso, cualquiera cosa te digo, gracias!

**Comment by surrealcristian** [comment]
Los widgets de summernote no quedaron muy bien visualmente , pero al menos ya están implementados.
Voy a intentar dejarlo bien visualmente.

**Comment by edvm** [comment]
Buenisimo Cristian, hay un issue asignado para la parte visual de los widgets: https://github.com/edvm/ffhq/issues/16 
Paso a Done esta tarea
