### ISSUE TITLE
Crear unittests de la vista que agrega un miembro a la cuadrilla

### ISSUE THREAD

**Issue by edvm** [edvm/ffhq#8]
Testear la vista cuadrilla.views.BomberoCreate. https://docs.djangoproject.com/en/1.7/topics/testing/tools/

**Comment by jcarizza** [comment]
Hice un test para probar que funcione el BomberoDetailView, pueden copiar ese tests para hacer el guardado.

@surrealcristian
@Theviajerock
@rafaelferrero

https://github.com/edvm/ffhq/commit/af9fee81c47440fc26d2812a338579ff7c1f9d9a

**Comment by edvm** [comment]
El test se deberia agregar en: cuadrilla/tests/test_cuadrilla.py (hay un ejemplo del test_bombero_detail_view en el mismo archivo que seguro viene de ayuda)
